# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'RestAPIExplorer' do

pod 'SalesforceMobileSDK-iOS', '~> 3.3'
# pod 'SalesforceMobileSDK-iOS', :path => '/Users/wmathurin/Development/github/wmathurin/SalesforceMobileSDK-iOS'

end


